-- DROP SCHEMA lembretes;

CREATE SCHEMA IF NOT EXISTS lembretes AUTHORIZATION postgres;


-- DROP SCHEMA commons;

CREATE SCHEMA IF NOT EXISTS commons AUTHORIZATION postgres;



-- lembretes.catalog_admin definition

-- Drop table

-- DROP TABLE lembretes.catalog_admin;

CREATE TABLE lembretes.catalog_admin (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	isdeleted bool NOT NULL DEFAULT false,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	code varchar NOT NULL,
	"name" varchar NOT NULL,
	other varchar NULL,
	parent int8 NULL,
	CONSTRAINT catalog_admin_pkey PRIMARY KEY (id),
	CONSTRAINT catalog_admin_parent_fk FOREIGN KEY (parent) REFERENCES lembretes.catalog_admin(id)
);

-- lembretes."role" definition

-- Drop table

-- DROP TABLE lembretes."role";

CREATE TABLE lembretes."role" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	isdeleted bool NOT NULL DEFAULT false,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	description varchar(200) NOT NULL,
	"name" varchar(20) NOT NULL,
	CONSTRAINT role_name_uk UNIQUE (name),
	CONSTRAINT role_pkey PRIMARY KEY (id)
);

-- lembretes.role_permission_module definition

-- Drop table

-- DROP TABLE lembretes.role_permission_module;

CREATE TABLE lembretes.role_permission_module (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	isdeleted bool NOT NULL DEFAULT false,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	module_id int8 NULL,
	permission_id int8 NULL,
	role_id int8 NULL,
	CONSTRAINT role_permission_module_pkey PRIMARY KEY (id)
);


-- lembretes.role_permission_module foreign keys

ALTER TABLE lembretes.role_permission_module ADD CONSTRAINT perm_mod_module_fk FOREIGN KEY (module_id) REFERENCES lembretes.catalog_admin(id);
ALTER TABLE lembretes.role_permission_module ADD CONSTRAINT perm_mod_permission_fk FOREIGN KEY (permission_id) REFERENCES lembretes.catalog_admin(id);
ALTER TABLE lembretes.role_permission_module ADD CONSTRAINT role_perm_role_fk FOREIGN KEY (role_id) REFERENCES lembretes.role(id);


-- lembretes."user" definition

-- Drop table

-- DROP TABLE lembretes."user";

CREATE TABLE lembretes."user" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	isdeleted bool NOT NULL DEFAULT false,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	address varchar(20) NULL,
	cell_phone varchar(10) NULL,
	last_name varchar(20) NOT NULL,
	"name" varchar(20) NOT NULL,
	"password" varchar(200) NULL,
	phone varchar(10) NULL,
	provider varchar(255) NULL,
	providerid varchar(255) NULL,
	user_name varchar(60) NOT NULL,
	role_id int8 NOT NULL,
	usergroup_id int8 NULL,
	CONSTRAINT user_pkey PRIMARY KEY (id),
	CONSTRAINT user_username_uk UNIQUE (user_name)
);


-- lembretes."user" foreign keys

ALTER TABLE lembretes."user" ADD CONSTRAINT user_role_fk FOREIGN KEY (role_id) REFERENCES lembretes.role(id);
ALTER TABLE lembretes."user" ADD CONSTRAINT usergroup_fk FOREIGN KEY (usergroup_id) REFERENCES lembretes.catalog_admin(id);

-- commons.mail definition

-- Drop table

-- DROP TABLE commons.mail;

CREATE TABLE commons.mail (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	creation_user int8 NOT NULL DEFAULT 0,
	isdeleted bool NOT NULL DEFAULT false,
	status bool NOT NULL DEFAULT true,
	update_date timestamp NULL,
	update_user int8 NULL,
	acronym varchar NULL,
	"content" varchar NOT NULL,
	subject varchar NOT NULL,
	CONSTRAINT mail_acronym_uk UNIQUE (acronym),
	CONSTRAINT mail_pkey PRIMARY KEY (id)
);
